Update clp core dependency to the latest OSS commit.
y-scope/clp-ffi-go pull request #7
Opened 2024-07-04 06:25 UTC by LinZhihao-723

# References

# Description

This PR updates clp core dependency to the latest commit. It contains the following changes:
1. Update on the build system config files for CMake and bazel to adapt source file structure changes in clp core
2. Update implementations in the Go ffi source files to adapt namespace and API changes in clp core ffi.

Note:
The latest clp commit has the IR format updated with UTC offset change packet. This PR doesn't handle the latest format yet (in both serializer and deserializer); another PR is expected after this PR gets merged to add support for UTC offset changes.

# Validation performed

1. Workflow passed with both cmake and bazel build succeeded
2. Passed all the linter checks

2024-07-04 07:09 UTC, davidlion requested changes

2024-07-04 07:09 UTC, davidlion commented on cpp/src/ffi_go/ir/deserializer.cpp
> +#include <string_utils/string_utils.hpp>
This is in the wrong place.

With the way things are (string_utils not built as a library) we should be able to include it with `#include <clp/components/core/src/clp/string_utils/string_utils.hpp>`.
If we switch string_utils to be built as a library (like in clp) then we need to add this to the third party library regex in the clang yaml configs.

2024-07-04 07:09 UTC, davidlion commented on cpp/src/ffi_go/search/wildcard_query.cpp
> +#include <string_utils/string_utils.hpp>
Same issue as cpp/src/ffi_go/ir/deserializer.cpp comment.

2024-07-05 06:03 UTC, davidlion submitted a review, later dismissed

2024-07-05 17:21 UTC, kirkrodrigues approved these changes

2024-07-05 17:37 UTC, merged